name: Update formulae
on:
  workflow_dispatch:
  schedule:
    - cron: '00 3 * * 1'

jobs:
  update:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install maltmill
        run: |
          brew install Songmu/tap/maltmill

      - name: Update formulae
        run: |
          maltmill -w rf.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: *.rb
          commit_message: Update formulae
